"""Publish ``reports/backtest.md`` as ``site/backtest.html``.

The backtest page is the proof asset a skeptical buyer checks: it publishes the
record WHOLE, including the five failing calibration buckets and the -5670.6
cost line. Its own header claims it is "regenerated by ``python -m
engine.backtest``, never hand-edited" — this module is what makes that claim
structurally true instead of a promise somebody has to keep by hand.

It existed as a promise for a while, and the promise broke exactly as you would
expect: regenerating backtest.md moved its timestamp, the published page did
not follow, and the page sat there claiming a generation date older than its
own source. That is a small thing that costs a lot on the one page whose entire
value is being verifiably faithful.

Design notes:

* The shell (CSS, masthead, footer) is a constant here, lifted verbatim from
  the hand-built page so the published design does not change.
* The converter handles only the constructs ``engine.backtest`` actually emits
  — headings, pipe tables, bullets, ordered lists, paragraphs, and inline
  bold/italic/code. It is deliberately not a general Markdown implementation:
  a small converter whose failures are visible beats a dependency whose
  rendering drifts. ``verify()`` is the backstop — it fails loudly if any
  figure in the source is missing from the output.

Usage::

    python -m render.backtest_site        # after python -m engine.backtest
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

from render.report import mark_svg

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "reports" / "backtest.md"
OUTPUT = REPO_ROOT / "site" / "backtest.html"

# Lifted verbatim from the hand-built page: same palette and type as every
# other surface (CLAUDE.md design NFR — one brand, one design system).
HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Beat Your League — The Full Backtest</title>
<meta name="description" content="Two seasons of graded calls — hits, misses, and the buckets that failed. The complete record behind the product.">
<meta property="og:title" content="Beat Your League — The Full Backtest">
<meta property="og:description" content="Two seasons of graded calls — hits, misses, and the buckets that failed. The complete record behind the product.">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Beat Your League">
<meta name="twitter:card" content="summary">
<!-- og:image needs the live absolute URL. After the domain exists, add:
     <meta property="og:image" content="https://YOUR-DOMAIN/og.png"> -->
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧾</text></svg>">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;800&family=Barlow:wght@400;500;700;800&display=swap" rel="stylesheet">
<style>
  :root{--navy:#101E33;--paper:#F6F4EE;--card:#FFF;--turf:#1E7A46;--flag:#F2C230;
    --brick:#B3402F;--slate:#5A6B80;--ink2:#33445C;--line:#D8D3C6;}
  *{margin:0;padding:0;box-sizing:border-box;}
  body{background:#E7E4DA;font-family:'Barlow',sans-serif;color:var(--navy);padding:14px 8px 44px;}
  .sheet{max-width:860px;margin:0 auto;background:var(--paper);border:1px solid var(--line);
    box-shadow:0 2px 18px rgba(16,30,51,.10);}
  header{background:linear-gradient(180deg,#182A45,var(--navy));color:var(--paper);padding:26px 28px;}
  header .brand{display:inline-flex;align-items:center;gap:9px;font-family:'Barlow Condensed';font-weight:800;font-size:15px;letter-spacing:.24em;
    text-transform:uppercase;color:var(--flag);}
  header .brand a{color:inherit;text-decoration:none;}
  header .brand svg.mark{width:22px;height:15px;flex:none;}
  header h1{font-family:'Barlow Condensed';font-weight:800;font-size:40px;text-transform:uppercase;margin-top:6px;}
  header p{margin-top:8px;font-size:14px;color:#C9D4E2;line-height:1.55;max-width:620px;}
  main{padding:8px 28px 34px;}
  main h1{display:none;}
  h2{font-family:'Barlow Condensed';font-weight:800;font-size:25px;text-transform:uppercase;
    margin:28px 0 8px;padding-top:14px;border-top:3px double var(--line);}
  h3{font-family:'Barlow Condensed';font-weight:800;font-size:19px;text-transform:uppercase;margin:20px 0 6px;}
  p{font-size:14.5px;line-height:1.6;color:var(--ink2);margin:8px 0;}
  ul{margin:8px 0 8px 20px;} li{font-size:14.5px;line-height:1.6;color:var(--ink2);margin:3px 0;}
  /* The page's own claim, drawn. */
  .calfig{margin:22px 0 6px;}
  .calfig svg{width:100%;height:auto;border:1px solid var(--line);background:#fff;}
  .calfig figcaption{margin-top:9px;font-size:13px;line-height:1.6;color:var(--slate);}
  table{width:100%;border-collapse:collapse;background:var(--card);border:2px solid var(--navy);
    font-size:13.5px;margin:12px 0;font-variant-numeric:tabular-nums;}
  th{background:var(--navy);color:#C9D4E2;font-family:'Barlow Condensed';font-weight:800;
    font-size:11.5px;letter-spacing:.1em;text-transform:uppercase;padding:8px 9px;text-align:left;}
  td{padding:8px 9px;border-top:1px solid #EDEAE1;}
  b{color:var(--navy);}
  footer{padding:18px 28px 26px;font-size:12px;color:var(--slate);line-height:1.6;
    border-top:3px double var(--line);}
</style>
</head>
<body>
<div class="sheet">
  <header>
    <div class="brand">""" + mark_svg("bylb") + """<a href="index.html">Beat Your League</a></div>
    <h1>The Full Backtest</h1>
    <p>Published whole, including the buckets that failed and the calls that cost points.
    This is the document the landing page cites — regenerated by
    <code>python -m engine.backtest</code>, never hand-edited.</p>
  </header>
"""

TAIL = """</main>
  <div style="padding:26px 28px;border-top:3px double var(--line);text-align:center;">
    <p style="margin:0 0 12px;font-size:15px;">That's the record, failures included.
    Your reports get graded the same way, in public, every Monday.</p>
    <a href="join/index.html" style="display:inline-block;background:var(--turf);color:#fff;
      text-decoration:none;font-family:'Barlow Condensed';font-weight:800;font-size:17px;
      letter-spacing:.1em;text-transform:uppercase;padding:13px 26px;">Pick your rival</a>
  </div>
  <footer><b>Beat Your League</b> — analysis, not picks. Every number here is reproducible
  from cached league data; the live record is on the public ledger.</footer>
</div>
</body>
</html>
"""


def _inline(text: str) -> str:
    """Escape, then apply the inline markup engine.backtest emits.

    Escaping happens FIRST and the replacements insert their own tags, so a
    stray ``<`` in the source can never become markup — the report is generated
    from league data, and league data is somebody else's text.
    """
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)
    out = re.sub(r"(?<![*\w])\*([^*]+)\*(?![*\w])", r"<em>\1</em>", out)
    return out


def _calibration_chart(head: list[str], body: list[list[str]]) -> str:
    """Draw the page's own claim.

    The whole argument of this document is "when we say 64%, roughly 64% of
    those calls hit" — and it was only ever tabulated. Six rows of percentages
    do not show a reader that stated confidence climbs from 52% to 84% while
    observed sits flat near 54%; one picture does, and that flat line IS the
    availability finding that made the shipping product gate on who is playing.

    Plots the UNCONDITIONAL table only. The availability-controlled table is a
    diagnostic (it conditions on an outcome unknowable at call time) and must
    never be drawn as if it were accuracy.
    """
    try:
        i_stated = head.index("Stated avg")
        i_obs = head.index("Observed")
        i_int = head.index("95% interval")
        i_n = head.index("Decided")
    except ValueError:
        return ""

    def num(cell: str) -> float | None:
        m = re.search(r"-?\d+(?:\.\d+)?", cell)
        return float(m.group(0)) if m else None

    points = []
    for row in body:
        if len(row) <= max(i_stated, i_obs, i_int, i_n):
            continue
        stated, obs, n = num(row[i_stated]), num(row[i_obs]), num(row[i_n])
        bounds = re.findall(r"\d+(?:\.\d+)?", row[i_int])
        if stated is None or obs is None or len(bounds) < 2:
            continue
        points.append((stated, obs, float(bounds[0]), float(bounds[1]),
                       int(n or 0), row[0]))
    if len(points) < 3:
        return ""

    # Fixed 45-90% window on both axes so the diagonal is a true 45 degrees and
    # the eye can read distance from it directly.
    lo, hi = 45.0, 90.0
    W, H, PAD = 560, 300, 42
    def x(v: float) -> float: return PAD + (v - lo) / (hi - lo) * (W - PAD - 14)
    def y(v: float) -> float: return H - PAD - (v - lo) / (hi - lo) * (H - PAD - 16)

    grid = []
    for tick in (50, 60, 70, 80, 90):
        grid.append(f'<line x1="{x(tick):.1f}" y1="{y(lo):.1f}" x2="{x(tick):.1f}" '
                    f'y2="{y(hi):.1f}" stroke="#D8D3C6" stroke-width="1"/>')
        grid.append(f'<line x1="{x(lo):.1f}" y1="{y(tick):.1f}" x2="{x(hi):.1f}" '
                    f'y2="{y(tick):.1f}" stroke="#D8D3C6" stroke-width="1"/>')
        grid.append(f'<text x="{x(tick):.1f}" y="{H - PAD + 15:.1f}" text-anchor="middle" '
                    f'font-size="10" fill="#5A6B80">{tick}%</text>')
        grid.append(f'<text x="{PAD - 8:.1f}" y="{y(tick) + 3:.1f}" text-anchor="end" '
                    f'font-size="10" fill="#5A6B80">{tick}%</text>')

    marks = []
    for stated, obs, lo_i, hi_i, n, label in points:
        cx = x(stated)
        marks.append(f'<line x1="{cx:.1f}" y1="{y(lo_i):.1f}" x2="{cx:.1f}" '
                     f'y2="{y(hi_i):.1f}" stroke="#B3402F" stroke-width="2" '
                     f'stroke-linecap="round" opacity=".5"/>')
        # area scales with the bucket's sample size, so a 37-call bucket cannot
        # look as solid as a 608-call one
        r = max(3.0, min(9.0, (n ** 0.5) / 3.0))
        marks.append(f'<circle cx="{cx:.1f}" cy="{y(obs):.1f}" r="{r:.1f}" '
                     f'fill="#B3402F" stroke="#F6F4EE" stroke-width="1.5">'
                     f'<title>stated {stated}% \u2192 observed {obs}% '
                     f'({n} decided calls, {label})</title></circle>')

    return (
        f'<figure class="calfig">'
        f'<svg viewBox="0 0 {W} {H}" role="img" '
        f'aria-label="Stated confidence against observed hit rate. Perfect '
        f'calibration is the diagonal. Observed stays near 54% while stated '
        f'climbs to 84%, so the number barely sorts.">'
        f'<rect width="{W}" height="{H}" fill="#FFFFFF"/>'
        f'{"".join(grid)}'
        f'<line x1="{x(lo):.1f}" y1="{y(lo):.1f}" x2="{x(hi):.1f}" y2="{y(hi):.1f}" '
        f'stroke="#1E7A46" stroke-width="2" stroke-dasharray="6 4"/>'
        f'<text x="{x(78):.1f}" y="{y(82):.1f}" font-size="10" font-weight="700" '
        f'fill="#1E7A46">perfect calibration</text>'
        f'{"".join(marks)}'
        f'<text x="{W / 2:.1f}" y="{H - 6:.1f}" text-anchor="middle" font-size="10.5" '
        f'font-weight="700" fill="#33445C">stated confidence</text>'
        f'<text x="12" y="{H / 2:.1f}" text-anchor="middle" font-size="10.5" '
        f'font-weight="700" fill="#33445C" '
        f'transform="rotate(-90 12 {H / 2:.1f})">observed hit rate</text>'
        f'</svg>'
        f'<figcaption>Each dot is a confidence bucket, sized by how many calls it '
        f'holds; the bar is its 95% interval. On the diagonal, stated equals '
        f'observed. Ours run flat near 54% while stated climbs to 84% \u2014 the '
        f'number barely sorts, and that gap is the availability blind spot '
        f'described above, which is why the shipping report only prints a '
        f'confidence once both players are confirmed active.</figcaption>'
        f'</figure>'
    )


def _alignment(cell: str) -> str:
    """Markdown's divider row carries the column alignment: `---:` is right,
    `:---:` is centre. Numbers belong right-aligned so their digits line up."""
    cell = cell.strip()
    if cell.endswith(":"):
        return "center" if cell.startswith(":") else "right"
    return "left"


def _is_divider(cells: list[str]) -> bool:
    return bool(cells) and all(re.fullmatch(r":?-{2,}:?", c.strip()) for c in cells)


def _split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def to_html(markdown: str) -> str:
    """Convert the backtest report body to HTML."""
    lines = markdown.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            level = min(len(heading.group(1)), 3)
            out.append(f"<h{level}>{_inline(heading.group(2))}</h{level}>")
            i += 1
            continue

        if stripped.startswith("|"):
            rows = []
            aligns: list[str] = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = _split_row(lines[i])
                if _is_divider(cells):
                    # The divider row IS the alignment spec. Discarding it left
                    # every figure on the page ragged-left, so columns of
                    # numbers could not be compared down their digits.
                    aligns = [_alignment(c) for c in cells]
                else:
                    rows.append(cells)
                i += 1
            if rows:
                head, *body = rows
                # Phones: a wide table scrolls inside its own container —
                # never the page body sideways.
                out.append('<div style="overflow-x:auto;-webkit-overflow-scrolling:touch">')
                out.append("<table>")
                def _style(idx: int) -> str:
                    align = aligns[idx] if idx < len(aligns) else "left"
                    return "" if align == "left" else f' style="text-align:{align}"'

                out.append("<tr>" + "".join(f"<th{_style(n)}>{_inline(c)}</th>"
                                            for n, c in enumerate(head)) + "</tr>")
                for row in body:
                    out.append("<tr>" + "".join(f"<td{_style(n)}>{_inline(c)}</td>"
                                                for n, c in enumerate(row)) + "</tr>")
                out.append("</table></div>")
                if head and head[0] == "Stated confidence":
                    out.append(_calibration_chart(head, body))
            continue

        bullet = re.match(r"^\s*[-*]\s+(.*)$", line)
        if bullet:
            out.append("<ul>")
            while i < len(lines) and re.match(r"^\s*[-*]\s+", lines[i]):
                item = re.sub(r"^\s*[-*]\s+", "", lines[i])
                out.append(f"<li>{_inline(item)}</li>")
                i += 1
            out.append("</ul>")
            continue

        if re.match(r"^\s*\d+\.\s+", line):
            out.append("<ol>")
            while i < len(lines) and re.match(r"^\s*\d+\.\s+", lines[i]):
                item = re.sub(r"^\s*\d+\.\s+", "", lines[i])
                out.append(f"<li>{_inline(item)}</li>")
                i += 1
            out.append("</ol>")
            continue

        # Paragraph: consume until a blank line or the start of another block.
        para = []
        while i < len(lines) and lines[i].strip() and not re.match(
                r"^(#{1,6}\s|\||\s*[-*]\s|\s*\d+\.\s)", lines[i]):
            para.append(lines[i].strip())
            i += 1
        if para:
            out.append(f"<p>{_inline(' '.join(para))}</p>")
    return "\n".join(out)


def verify(markdown: str, page: str) -> list[str]:
    """Every figure in the source must survive into the page.

    This is the whole point of the module: the page claims to be a faithful
    publication, so a conversion that silently dropped a row — especially a
    FAILING row — would be worse than no generator at all.
    """
    problems: list[str] = []
    text = re.sub(r"<[^>]+>", " ", page)
    figures = set(re.findall(r"-?\d+\.\d+%?|\b\d{3,5}\b", markdown))
    missing = sorted(f for f in figures if f not in text)
    if missing:
        problems.append(f"{len(missing)} figure(s) missing from the page: {missing[:8]}")
    # The failures specifically: this page exists to publish them.
    if markdown.count("| off") and ">off<" not in page:
        problems.append("the failing calibration buckets did not survive conversion")
    for required in ("53.5%", "Limitations"):
        if required.lower() not in text.lower():
            problems.append(f"missing required content: {required!r}")
    # <ol> draws its own numbers, so a source list that does not start at 1 and
    # run consecutively would be silently RENUMBERED on the published page —
    # a faithful-publication failure that looks like nothing at all.
    groups, current = [], []
    for line in markdown.splitlines():
        match = re.match(r"^\s*(\d+)\.\s", line)
        if match:
            current.append(int(match.group(1)))
        elif current:
            groups.append(current)
            current = []
    if current:
        groups.append(current)
    for group in groups:
        if group != list(range(1, len(group) + 1)):
            problems.append(
                f"ordered list {group} does not run 1..n, so <ol> would renumber it")
    return problems


def build(source: Path = SOURCE) -> str:
    markdown = source.read_text(encoding="utf-8")
    page = HEAD + "  <main>\n" + to_html(markdown) + "\n" + TAIL
    problems = verify(markdown, page)
    if problems:
        raise SystemExit("refusing to publish an unfaithful backtest page:\n  "
                         + "\n  ".join(problems))
    return page


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true",
                        help="fail if the published page is stale, without writing")
    args = parser.parse_args(argv)

    if not args.source.is_file():
        print(f"{args.source} not found — run `python -m engine.backtest` first",
              file=sys.stderr)
        return 1
    page = build(args.source)

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current != page:
            print(f"{args.output} is out of date with {args.source.name} — "
                  f"run `python -m render.backtest_site`", file=sys.stderr)
            return 1
        print(f"{args.output.name} is up to date with {args.source.name}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(page, encoding="utf-8")
    print(f"Wrote {args.output.relative_to(REPO_ROOT)} from "
          f"{args.source.relative_to(REPO_ROOT)} ({len(page):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
