"""Publish ``reports/backtest.md`` as ``site/backtest.html``.

The backtest page is the proof asset a skeptical buyer checks: it publishes the
record WHOLE, including the five failing calibration buckets and the -5670.6
cost line. Its own header claims it is "regenerated by ``python -m
engine.backtest``, never hand-edited" — this module is what makes that claim
structurally true instead of a promise somebody has to keep by hand.

It existed as a promise for a while, and the promise broke exactly as you would
expect: regenerating backtest.md moved its timestamp, the published page did
not follow, and the page sat there claiming a generation date older than its
own source. That is a small thing that costs a lot on the one page whose entire
value is being verifiably faithful.

Design notes:

* The shell (CSS, masthead, footer) is a constant here, lifted verbatim from
  the hand-built page so the published design does not change.
* The converter handles only the constructs ``engine.backtest`` actually emits
  — headings, pipe tables, bullets, ordered lists, paragraphs, and inline
  bold/italic/code. It is deliberately not a general Markdown implementation:
  a small converter whose failures are visible beats a dependency whose
  rendering drifts. ``verify()`` is the backstop — it fails loudly if any
  figure in the source is missing from the output.

Usage::

    python -m render.backtest_site        # after python -m engine.backtest
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "reports" / "backtest.md"
OUTPUT = REPO_ROOT / "site" / "backtest.html"

# Lifted verbatim from the hand-built page: same palette and type as every
# other surface (CLAUDE.md design NFR — one brand, one design system).
HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Beat Your League — The Full Backtest</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;800&family=Barlow:wght@400;500;700;800&display=swap" rel="stylesheet">
<style>
  :root{--navy:#101E33;--paper:#F6F4EE;--card:#FFF;--turf:#1E7A46;--flag:#F2C230;
    --brick:#B3402F;--slate:#5A6B80;--ink2:#33445C;--line:#D8D3C6;}
  *{margin:0;padding:0;box-sizing:border-box;}
  body{background:#E7E4DA;font-family:'Barlow',sans-serif;color:var(--navy);padding:14px 8px 44px;}
  .sheet{max-width:860px;margin:0 auto;background:var(--paper);border:1px solid var(--line);
    box-shadow:0 2px 18px rgba(16,30,51,.10);}
  header{background:linear-gradient(180deg,#182A45,var(--navy));color:var(--paper);padding:26px 28px;}
  header .brand{font-family:'Barlow Condensed';font-weight:800;font-size:15px;letter-spacing:.24em;
    text-transform:uppercase;color:var(--flag);}
  header .brand a{color:inherit;text-decoration:none;}
  header h1{font-family:'Barlow Condensed';font-weight:800;font-size:40px;text-transform:uppercase;margin-top:6px;}
  header p{margin-top:8px;font-size:14px;color:#C9D4E2;line-height:1.55;max-width:620px;}
  main{padding:8px 28px 34px;}
  main h1{display:none;}
  h2{font-family:'Barlow Condensed';font-weight:800;font-size:25px;text-transform:uppercase;
    margin:28px 0 8px;padding-top:14px;border-top:3px double var(--line);}
  h3{font-family:'Barlow Condensed';font-weight:800;font-size:19px;text-transform:uppercase;margin:20px 0 6px;}
  p{font-size:14.5px;line-height:1.6;color:var(--ink2);margin:8px 0;}
  ul{margin:8px 0 8px 20px;} li{font-size:14.5px;line-height:1.6;color:var(--ink2);margin:3px 0;}
  table{width:100%;border-collapse:collapse;background:var(--card);border:2px solid var(--navy);
    font-size:13.5px;margin:12px 0;font-variant-numeric:tabular-nums;}
  th{background:var(--navy);color:#C9D4E2;font-family:'Barlow Condensed';font-weight:800;
    font-size:11.5px;letter-spacing:.1em;text-transform:uppercase;padding:8px 9px;text-align:left;}
  td{padding:8px 9px;border-top:1px solid #EDEAE1;}
  b{color:var(--navy);}
  footer{padding:18px 28px 26px;font-size:12px;color:var(--slate);line-height:1.6;
    border-top:3px double var(--line);}
</style>
</head>
<body>
<div class="sheet">
  <header>
    <div class="brand"><a href="index.html">&larr; Beat Your League</a></div>
    <h1>The Full Backtest</h1>
    <p>Published whole, including the buckets that failed and the calls that cost points.
    This is the document the landing page cites — regenerated by
    <code>python -m engine.backtest</code>, never hand-edited.</p>
  </header>
"""

TAIL = """</main>
  <footer><b>Beat Your League</b> — analysis, not picks. Every number here is reproducible
  from cached league data; the live record is on the public ledger.</footer>
</div>
</body>
</html>
"""


def _inline(text: str) -> str:
    """Escape, then apply the inline markup engine.backtest emits.

    Escaping happens FIRST and the replacements insert their own tags, so a
    stray ``<`` in the source can never become markup — the report is generated
    from league data, and league data is somebody else's text.
    """
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)
    out = re.sub(r"(?<![*\w])\*([^*]+)\*(?![*\w])", r"<em>\1</em>", out)
    return out


def _is_divider(cells: list[str]) -> bool:
    return bool(cells) and all(re.fullmatch(r":?-{2,}:?", c.strip()) for c in cells)


def _split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def to_html(markdown: str) -> str:
    """Convert the backtest report body to HTML."""
    lines = markdown.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            level = min(len(heading.group(1)), 3)
            out.append(f"<h{level}>{_inline(heading.group(2))}</h{level}>")
            i += 1
            continue

        if stripped.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = _split_row(lines[i])
                if not _is_divider(cells):
                    rows.append(cells)
                i += 1
            if rows:
                head, *body = rows
                out.append("<table>")
                out.append("<tr>" + "".join(f"<th>{_inline(c)}</th>" for c in head) + "</tr>")
                for row in body:
                    out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>")
                out.append("</table>")
            continue

        bullet = re.match(r"^\s*[-*]\s+(.*)$", line)
        if bullet:
            out.append("<ul>")
            while i < len(lines) and re.match(r"^\s*[-*]\s+", lines[i]):
                item = re.sub(r"^\s*[-*]\s+", "", lines[i])
                out.append(f"<li>{_inline(item)}</li>")
                i += 1
            out.append("</ul>")
            continue

        if re.match(r"^\s*\d+\.\s+", line):
            out.append("<ol>")
            while i < len(lines) and re.match(r"^\s*\d+\.\s+", lines[i]):
                item = re.sub(r"^\s*\d+\.\s+", "", lines[i])
                out.append(f"<li>{_inline(item)}</li>")
                i += 1
            out.append("</ol>")
            continue

        # Paragraph: consume until a blank line or the start of another block.
        para = []
        while i < len(lines) and lines[i].strip() and not re.match(
                r"^(#{1,6}\s|\||\s*[-*]\s|\s*\d+\.\s)", lines[i]):
            para.append(lines[i].strip())
            i += 1
        if para:
            out.append(f"<p>{_inline(' '.join(para))}</p>")
    return "\n".join(out)


def verify(markdown: str, page: str) -> list[str]:
    """Every figure in the source must survive into the page.

    This is the whole point of the module: the page claims to be a faithful
    publication, so a conversion that silently dropped a row — especially a
    FAILING row — would be worse than no generator at all.
    """
    problems: list[str] = []
    text = re.sub(r"<[^>]+>", " ", page)
    figures = set(re.findall(r"-?\d+\.\d+%?|\b\d{3,5}\b", markdown))
    missing = sorted(f for f in figures if f not in text)
    if missing:
        problems.append(f"{len(missing)} figure(s) missing from the page: {missing[:8]}")
    # The failures specifically: this page exists to publish them.
    if markdown.count("| off") and ">off<" not in page:
        problems.append("the failing calibration buckets did not survive conversion")
    for required in ("53.5%", "Limitations"):
        if required.lower() not in text.lower():
            problems.append(f"missing required content: {required!r}")
    # <ol> draws its own numbers, so a source list that does not start at 1 and
    # run consecutively would be silently RENUMBERED on the published page —
    # a faithful-publication failure that looks like nothing at all.
    groups, current = [], []
    for line in markdown.splitlines():
        match = re.match(r"^\s*(\d+)\.\s", line)
        if match:
            current.append(int(match.group(1)))
        elif current:
            groups.append(current)
            current = []
    if current:
        groups.append(current)
    for group in groups:
        if group != list(range(1, len(group) + 1)):
            problems.append(
                f"ordered list {group} does not run 1..n, so <ol> would renumber it")
    return problems


def build(source: Path = SOURCE) -> str:
    markdown = source.read_text(encoding="utf-8")
    page = HEAD + "  <main>\n" + to_html(markdown) + "\n" + TAIL
    problems = verify(markdown, page)
    if problems:
        raise SystemExit("refusing to publish an unfaithful backtest page:\n  "
                         + "\n  ".join(problems))
    return page


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true",
                        help="fail if the published page is stale, without writing")
    args = parser.parse_args(argv)

    if not args.source.is_file():
        print(f"{args.source} not found — run `python -m engine.backtest` first",
              file=sys.stderr)
        return 1
    page = build(args.source)

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current != page:
            print(f"{args.output} is out of date with {args.source.name} — "
                  f"run `python -m render.backtest_site`", file=sys.stderr)
            return 1
        print(f"{args.output.name} is up to date with {args.source.name}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(page, encoding="utf-8")
    print(f"Wrote {args.output.relative_to(REPO_ROOT)} from "
          f"{args.source.relative_to(REPO_ROOT)} ({len(page):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
